//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yechtch.IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class configemail
    {
        public int id { get; set; }
        public string monitoritemcode { get; set; }
        public string address { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<bool> ssl { get; set; }
        public string account { get; set; }
        public string password { get; set; }
    }
}
