//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yechtch.IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class configdb
    {
        public int id { get; set; }
        public string dbname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string url { get; set; }
        public string dbcode { get; set; }
        public Nullable<int> dbtype { get; set; }
        public string companycode { get; set; }
        public string database { get; set; }
    }
}
