//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yechtch.IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailcurrent
    {
        public int id { get; set; }
        public Nullable<float> uid { get; set; }
        public Nullable<System.DateTime> internaldate { get; set; }
        public string subject { get; set; }
        public string bodyhtml { get; set; }
        public string bodytext { get; set; }
        public string vg { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
