//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yechtch.IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitoritemlastresult
    {
        public int id { get; set; }
        public string companycode { get; set; }
        public string monitorgroupcode { get; set; }
        public string monitorcode { get; set; }
        public string monitoritemcode { get; set; }
        public Nullable<decimal> resultvalue { get; set; }
        public string resultdesc { get; set; }
        public Nullable<int> resultstatus { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public Nullable<System.DateTime> nextdatetime { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
